name: Update Proxy Links

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch full history
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script
      run: python proxy_link_generator.py
    - name: Commit and push if changed
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add proxy_links.txt
        git diff --quiet && git diff --staged --quiet || (
          git commit -m "Update proxy links"
          git push https://x-access-token:${GH_PAT}@github.com/wpilotcn/ProxyGenerator.git
        )
